description = "Initializ Distroless base image with buildpacks for Go, NodeJS, Python, Ruby, Java, .NET Core, Apache HTTPD, NGINX and Procfile"

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/dotnet-core:1.1.0"
  version = "1.1.0"

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/go:2.0.5"
  version = "2.0.5"

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/java-native-image:9.1.0"
  version = "9.1.0"

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/java:9.9.2"
  version = "9.9.2"

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/nodejs:3.0.8"
  version = "3.0.8"

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/procfile:5.6.22"
  version = "5.6.22"

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/python:4.0.9"
  version = "4.0.9"

[[buildpacks]]
  uri = "docker://docker.io/initializbuildpacks/web-servers:1.0.19"
  version = "1.0.19"

[lifecycle]
  version = "0.20.4"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/dotnet-core"
    version = "1.1.0"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/go"
    version = "2.0.5"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/python"
    version = "4.0.9"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/web-servers"
    version = "1.0.19"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/java-native-image"
    version = "9.1.0"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/java"
    version = "9.9.2"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/nodejs"
    version = "3.0.8"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/procfile"
    version = "5.6.22"

[stack]
  build-image = "docker.io/initializbuildpacks/securepacks-build:0.0.3"
  id = "Initializ Distroless Stack"
  run-image = "initializbuildpacks/securepacks-run:latest"
  run-image-mirrors = []
